name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --dev

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests

      - name: Run Ruff linter (with autofix)
        id: ruff-check
        run: |
          source .venv/bin/activate
          ruff check src tests --fix

      - name: Run Ruff formatter
        id: ruff-format
        run: |
          source .venv/bin/activate
          ruff format src tests

      - name: Check for type errors
        run: |
          source .venv/bin/activate
          mypy src