name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install uv wheel
          uv sync

      - name: Set version from workflow input
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          sed -i "s/^version = .*/version = \"${{ github.event.inputs.version }}\"/" pyproject.toml

      - name: Build package
        run: |
          source .venv/bin/activate
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          source .venv/bin/activate
          uv add twine
          twine upload dist/*